import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

const LANGUAGE_LS_KEY = "appLanguage";

const translations = {
  hu: {

    homeUpper: "OTTHON",
        equipment: "Felszerelés",
        stats: "Statisztikák",
        inventory: "Leltár",
        clickForDetails: "Kattints a részletekhez",
        emptySlot: "Üres slot",
        empty: "Üres",
        inventoryEmpty: "Az inventory üres",
        selected: "Kiválasztott",
        equip: "Felvétel",
        unequip: "Levétel",
        selectItem: "Válassz ki egy tárgyat",
        deck: "Deck",
        deckNotSavedYet: "*jelenleg nem mentődik el a deck ha kilépsz*",
        capacity: "Kapacitás",
        availableAbilities: "Elérhető képességek",
        activeDeck: "Aktív Deck",
        emptyDeck: "Üres Deck",
        cancelUpper: "MÉGSE",
        saveDeck: "DECK MENTÉS",
        exitHouse: "Kilépés a házból",
        spellbook: "Varázskönyv",
        inventoryLabel: "Leltár",
        statistics: "Statisztikák",
        level: "Szint",
        hp: "Életerő",
        strength: "Erő",
        intellect: "Intelligencia",
        defense: "Védelem",
        gold: "Arany",
        houseTutInventory: "Kattints a Leltárra (felszerelés kezelése).",
        houseTutDeck: "Kattints a Szekrényre (deck szerkesztés).",
        houseTutStats: "Kattints a Statisztikákra (stat pontok).",
        houseTutExit: "Kattints a Kilépésre (vissza a Hubba).",

    menu: "Menü",
    settings: "Beállítások",
    logout: "Kijelentkezés",
    logoutPlaceholder: "Kijelentkezés (placeholder)",

    travel: "Utazás",
    blacksmith: "Kovács",
    quests: "Küldetések",
    shop: "Bolt",
    home: "Otthon",

    welcome: "Üdvözöllek!",
    hubIntroLine1:
      "Ez az a hely, ahol felkészülhetsz a következő utadra. Itt fejleszthetsz, vásárolhatsz, küldetéseket vállalhatsz, és rendbe teheted, amid van.",
    hubIntroLine2: "Ha készen állsz, továbbléphetsz az utazás felé.",
    continue: "Tovább",

    tutorialHome: "Kattints az OTTHON-ra (Inventory / Deck / Stats).",
    tutorialBlacksmith: "Kattints a KOVÁCS-ra (fejlesztések).",
    tutorialShop: "Kattints a BOLT-ra (vásárlás).",
    tutorialQuests: "Kattints a KÜLDETÉSEK-re.",
    tutorialTravel: "Kattints az UTAZÁS-ra (kaland indítása).",

    tab_sound: "Hang",
    tab_language: "Nyelv",
    tab_profile: "Profil",
    tab_admin: "Admin mód",

    soundTitle: "HANG",
    languageTitle: "NYELV",
    profileTitle: "PROFIL",
    adminTitle: "ADMIN MÓD",

    music: "Zene",
    effects: "Effektek",
    master: "Master",

    saveLaterNote: "Placeholder: később ténylegesen mentjük/alkalmazzuk.",
    languageSaveNote: "A nyelv azonnal vált és localStorage-ba mentődik.",

    profileImage: "Profilkép",
    noImage: "(Nincs kép)",
    unknown: "Ismeretlen",
    statsTitle: "STATISZTIKÁK",
    registeredAt: "Regisztráció ideje",

    enemiesDefeated: "Legyőzött ellenfelek",
    bossesDefeated: "Legyőzött bossok",
    battlesPlayed: "Lejátszott csaták",
    battlesWon: "Megnyert csaták",
    totalDamage: "Összes sebzés",
    totalDamageTaken: "Kapott sebzés",

    statsBackendNote: "(Ha még nem küldöd a statokat a backendből, akkor itt “—” lesz.)",

    editUsernameTitle: "Felhasználónév módosítása",
    editEmailTitle: "Email módosítása",
    changeUsername: "FELHASZNÁLÓNÉV VÁLTOZTATÁS",
    changeEmail: "EMAIL VÁLTOZTATÁS",
    newValue: "Új érték",
    cancel: "Mégse",
    change: "Változtat",
    close: "Bezárás",
    exampleEmail: "pl. valami@email.com",
    exampleUsername: "pl. uj_felhasznalo",

    adminNote:
      "Írd be az új értéket (SET). Üres mező = nem változik. Max HP mentéskor HP is fullra tölt.",
    goldSet: "Gold (SET)",
    maxHpSet: "Max HP (SET)",
    xpSet: "XP (SET)",
    levelSet: "Level (SET)",
    strengthSet: "Strength (SET)",
    intellectSet: "Intellect (SET)",
    defenseSet: "Defense (SET)",
    save: "Mentés",
    saving: "Mentés...",
    loadingSkip: "Loading screen skip",
    loadingSkipOn: "ON: az utazás/loading képernyő azonnal skipelődik.",
    loadingSkipOff: "OFF: az utazás/loading képernyő visszaszámlál.",
    statUpgradeTitle: "Stat Fejlesztés",
unspentPoints: "Elosztható pontok",
strengthShort: "Erő (STR)",
intellectShort: "Intelligencia (INT)",
defenseShort: "Védelem (DEF)",
hpUpgradeLabel: "Életerő (Max HP +5)",
statSaveError: "Nem sikerült menteni a statokat.",
weapon: "Fegyver",
helmet: "Sisak",
armor: "Páncél",
accessory: "Kiegészítő",
levelUpper: "SZINT",
goldUpper: "ARANY",
hpUpper: "HP",
goldLower: "arany",
healing: "Gyógyítás",
buyUpper: "VESZ",
sellUpper: "ELAD",
shopBuyFailed: "Sikertelen vásárlás",
shopSellFailed: "Sikertelen eladás",
shopHealFailed: "Sikertelen gyógyítás",
shopStatsLoading: "Még tölt a stat (full-stats).",
shopFullHp: "Full HP-n vagy.",
chooseHeroTitle: "Válassz egy hőst",
chooseHeroAlert: "Válassz egy hőst!",
notLoggedInError: "Hiba: nem vagy bejelentkezve.",
saveClassError: "Nem sikerült menteni a kasztot!",
serverError: "Szerver hiba történt!",
unknownClass: "Ismeretlen kaszt.",
detailsUp: "Részletek ▲",
detailsDown: "Részletek ▼",
roleLabel: "Szerep",
strengthLabel: "Erősség",
weaknessLabel: "Gyengeség",
createButton: "Létrehozás",
classLoadErrorConsole: "Nem sikerült betölteni a kasztokat:",

warriorName: "Harcos",
warriorShort: "Masszív közelharcos, aki többféle irányba is építhető: lehet biztonságos bruiser, agresszív sebző vagy kitartó túlélő.",
warriorRole: "Sokoldalú frontline",
warriorStrength: "Rugalmas buildlehetőségek, stabil jelenlét és jó alkalmazkodás különböző helyzetekhez.",
warriorWeakness: "Rossz döntésekkel könnyen nyomás alá kerülhet.",

mageName: "Varázsló",
mageShort: "Pusztító varázshasználó, aki nagy sebzéssel rendelkezik de kevés hibát engedhet meg magának.",
mageRole: "Burst / control mágus",
mageStrength: "Magas sebzés, erős spellhatások és veszélyes kombók, amelyek gyorsan eldönthetnek egy harcot.",
mageWeakness: "Törékenyebb.",

archerName: "Íjász",
archerShort: "Stabil távolsági sebző, aki folyamatos nyomás alatt tartja az ellenfelet, miközben a petje sok beérkező sebzést felfog helyette.",
archerRole: "Stabil ranged DPS",
archerStrength: "Megbízható, folyamatos sebzés és nagyobb biztonság a pet támogatása miatt.",
archerWeakness: "Ha a pet kiesik vagy nem tudja megtartani a nyomást, sokkal sebezhetőbbé válik.",
menu: "Menü",
settings: "Beállítások",
logout: "Kijelentkezés",
logoutPlaceholder: "Kijelentkezés (placeholder)",
hubImageAlt: "hub",
player: "player",
welcome: "Üdvözöllek!",
hubIntroLine1:
  "Ez az a hely, ahol felkészülhetsz a következő utadra. Itt fejleszthetsz, vásárolhatsz, küldetéseket vállalhatsz, és rendbe teheted, amid van.",
hubIntroLine2: "Ha készen állsz, továbbléphetsz az utazás felé.",
continue: "Tovább",
travel: "Utazás",
blacksmith: "Kovács",
quests: "Küldetések",
shop: "Bolt",
home: "Otthon",
hubTutHome: "Kattints az OTTHON-ra (Inventory / Deck / Stats).",
hubTutBlacksmith: "Kattints a KOVÁCS-ra (fejlesztések).",
hubTutShop: "Kattints a BOLT-ra (vásárlás).",
hubTutQuests: "Kattints a KÜLDETÉSEK-re.",
hubTutTravel: "Kattints az UTAZÁS-ra (kaland indítása).",
loading: "Betöltés...",
upgradeGoldInfo: "Fejlesztésre fordítható arany:",
noUpgradeableItems: "Nincs tovább fejleszthető tárgyad.",
currentItem: "Jelenlegi tárgy",
upgradedItem: "Fejlesztett tárgy",
upgradeCost: "Fejlesztés költsége",
notEnoughGoldForUpgrade: "Nincs elég aranyod a fejlesztéshez.",
processing: "Feldolgozás...",
upgrade: "Fejlesztés",
blacksmithUpgradeFailed: "A fejlesztés nem sikerült.",
blacksmithServerError: "Hiba a szerverrel való kapcsolatban.",
networkError: "Hálózati hiba.",
loginTitle: "Bejelentkezés",
registerTitle: "Regisztráció",
loginSubtitle: "*Adj meg egy felhasználónevet vagy email címet és jelszót a belépéshez*",
registerSubtitle: "*Hozz létre egy új fiókot*",
usernamePlaceholder: "Felhasználónév",
identifierPlaceholder: "Felhasználónév vagy email",
emailPlaceholder: "Email",
passwordPlaceholder: "Jelszó",
confirmPasswordPlaceholder: "Jelszó megerősítése",
registerButton: "REGISZTRÁCIÓ",
continueUpper: "TOVÁBB",
alreadyHaveAccount: "Van már fiókod?",
switchToLogin: "Jelentkezz be",
noAccountYet: "Nincs még fiókod?",
switchToRegister: "Regisztrálj",
loginNeedIdentifier: "Adj meg egy felhasználónevet vagy email címet!",
loginNeedPassword: "Adj meg egy jelszót!",
loginNeedEmail: "Adj meg egy email címet!",
loginInvalidEmail: "Érvénytelen email formátum!",
loginPasswordsDontMatch: "A jelszavak nem egyeznek!",
registerFailed: "Sikertelen regisztráció!",
registerLoginFailed: "Regisztráltál, de a bejelentkezés nem sikerült.",
loginFailed: "Hibás bejelentkezési adatok!",
emptyDeck: "Üres pakli",
mana: "Mana",
manaAbilities: "Mana Képességek",
clickToRelease: "Kattints a használathoz",
notEnoughMana: "Nincs elég mana",
back: "Vissza",
tauntActive: "TAUNT AKTÍV",
petTaunt: "PET TAUNT",
dead: "HALOTT",
newEnemyUpper: "ÚJ ELLENSÉG",
approachingUpper: "KÖZELEDIK...",
remainingEnemiesUpper: "MARADÉK ELLENSÉGEK",
fightUpper: "HARC",
noLoadedPlayer: "Nincs betöltött játékos. Jelentkezz be újra.",
combatBegins: "A RITUÁLÉ ELKEZDŐDIK...",
passTurnUpper: "PASSZOLÁS",
stamina: "Stamina",
hits: "Találatok",
taunt: "Taunt",
turns: "kör",
defeatUpper: "VERESÉG...",
victoryUpper: "GYŐZELEM!",
combatLogEvasionActive: "{card}: {turns} körig {percent}% eséllyel kitérsz!",
combatLogEvadedEnemyAttack: "Kitértél! {enemy} mellé üt. ({percent}%)",
combatLogEvasionFailed: "Megpróbáltál kitérni {enemy} elől, de nem sikerült. ({percent}%)",
combatTutEnemyTitle: "ELLENSÉG",
combatTutEnemyText: "Itt látod az enemy HP-t és az affixeket.",
combatTutLogTitle: "COMBAT LOG",
combatTutLogText: "Itt látod, mi történt.",
combatTutCardsTitle: "KÁRTYÁK",
combatTutCardsText: "Kattints egy lapra. 1 lap = 1 kör, utána az enemy jön.",
combatTutManaTitle: "MANA",
combatTutManaText: "Minden kártya után +1 mana. 5-től nyithatod a Mana Képességeket.",
combatTutPetTitle: "PET TAUNT",
combatTutPetText: "A Taunttal a pet kapja a találatokat pár körig. Utána cooldown.",
combatTutPassiveTitle: "PASSZÍV",
combatTutPassiveText: "Warrior: minél kevesebb HP-d van, annál nagyobbat ütsz, de többet is kapsz.",

combatLogGhostPhase: "Ghost: Phase – sebezhetetlen 1 körre!",
combatLogLichIceLance: "Lich Mage: Ice Lance – Weaken (1 kör).",
combatLogLichArcaneWard: "Lich Mage: Arcane Ward – a következő találat csökkentve!",
combatLogBanditGuard: "Bandit: Guard – a következő találat csökkentve!",

combatLogTravelPoisoned: "Utazási event: megmérgeződtél ({turns} kör).",

combatLogArcaneDamage: "{name}: {dmg} sebzés.",
combatLogArcaneFullHeal: "{name}: teljes gyógyítás.",
combatLogArcaneBigDamage: "{name}: {dmg} brutális sebzés!",

combatLogNotEnoughPetTauntStamina: "Nincs elég stamina a Pet Taunthoz!",
combatLogPassedTurn: "Passzoltál.",
combatLogPetTauntActivated: "Pet Taunt aktiválva ({turns} kör). Cooldown: {cooldown}.",
combatLogPetBite: "Pet Bite: {dmg} sebzés!",

combatLogShieldedGuardActive: "{enemy} [Shielded] – Guard aktív ({hits} találat).",
combatLogEnemyPhaseBlocksAttack: "{enemy} Phase-ben van – a támadás lepattan!",
combatLogWeakenReducedDamage: "Weaken: csökkentett sebzés!",
combatLogBerserkerRageDamage: "Berserker Rage: +{percent}% sebzés ({hp}/{maxHp} HP).",
combatLogExecute: "Crushing Blow – kivégzés!",
combatLogRallyingShoutBuff: "A Rallying Shout erősíti a támadásod!",
combatLogEnemyGuardReducedHit: "{enemy} Guard: csökkentett találat!",
combatLogCardDealsDamage: "{card} → {enemy} kap {dmg} sebzést{crit}.",
combatLogCritSuffix: " (KRITIKUS!)",
combatLogDrainLifeHeal: "Drain Life gyógyít: +{heal} HP.",
combatLogEnemyPoisoned: "{enemy} megmérgezve: {dmg} sebzés {turns} körön át.",
combatLogEnemyBleeding: "Vérzés! ({stacks} stack) {enemy} minden körben sebződik.",
combatLogEnemyBurning: "{enemy} égni kezd: {dmg} sebzés {turns} körön át.",
combatLogEnemyStunImmune: "{enemy} még {turns} körig nem stunolható!",
combatLogEnemyStunnedSkip: "{enemy} elkábult, kihagyja a következő körét!",
combatLogEnemyVulnerable: "{enemy} sebezhetővé válik: +{percent}% sebzést kap {turns} körig!",
combatLogTravelDamageBonus: "Utazási hatás: +{percent}% sebzés",

combatLogEvasionActive: "{card}: kitérés {turns} körig!",
combatLogDefendingActiveTurns: "{card}: védekezés aktiválva {turns} körre!",
combatLogDefendingActive: "Védekezés aktiválva – a következő ütés csökkentve.",
combatLogParryStun: "Parry! {enemy} elkábul, kihagyja a körét!",
combatLogCardPetTaunt: "Pet Taunt: a mob a petet üti ({turns} kör).",
combatLogCardHeals: "{card}: +{heal} HP.",
combatLogDamageBuff: "{card}: a következő {turns} támadásod +{percent}% sebzést okoz!",
combatLogMendPet: "Mend Pet: +{heal} HP (Pet: {hp}/{maxHp})",
combatLogWeakenEnded: "Weaken elmúlt.",

combatLogVictoryRewards: "Győzelem! +{gold} arany, +{xp} XP.",

combatLogPlagueAuraPoison: "{enemy} [Plague Aura] – megmérgez ({turns} kör).",
combatLogPoisonDamagePlayer: "Méreg sebzés: {dmg} (Te – {hp} HP).",
combatLogBurnDamageEnemy: "Égés sebzés: {dmg} ({enemy} – {hp} HP).",
combatLogPoisonDamageEnemy: "Méreg sebzés: {dmg} ({enemy} – {hp} HP).",
combatLogBleedDamageEnemy: "Vérzés: {dmg} sebzés ({percent}%).",
combatLogEnemyStillStunned: "{enemy} elkábulva marad, kihagyja a körét!",
combatLogArcaneSurgeEnded: "Az Arcane Surge hatása elmúlt.",
combatLogEvadedEnemyAttack: "Kitértél! {enemy} mellé üt.",
combatLogPetGuard: "Pet Guard! A pet tompította az ütést.",
combatLogEnemyHitsPet: "{enemy} a petet üti ({dmg} sebzés). (Pet: {hp}/{maxHp})",
combatLogEnemyAttacksPlayer: "{enemy} támad ({dmg} sebzés).",

combatLogEnemyAmbushed: "A {enemy} kihívott téged!",
combatLogEnemyAmbushedReinforcements: "{enemy} megtámadott! (ERŐSÍTÉS: +{count} ellenség közeleg...)",
combatLogEnemyDefeatedContinue: "{enemy} legyőzve...",
combatLogNewEnemyStepsIn: "! Új ellenfél lép a helyére: {enemy} !",

combatLogNotEnoughStamina: "Nincs elég stamina! ({cost} kell)",
travelInProgress: "Utazás folyamatban",
clickForNewTip: "Kattints új tippért!",
loadingTip: "Tipp betöltése...",
tipsErrorConsole: "Tippek hiba:",
pathFightTooltip: "Harccal teli ösvény",
pathEliteTooltip: "Veszélyes erejű ellenfél",
pathMysteryTooltip: "Ismeretlen esemény",
pathRestTooltip: "Megnyugvás és gyógyulás",
pathIntroWord1: "VÁLASSZ",
pathIntroWord2: "EGY",
pathIntroWord3: "ÖSVÉNYT",
pathIconAlt: "ösvény ikon",
eventWizardTitle: "Vándor varázsló",
eventWizardStory:
  "Az út porában egy köpenyes varázsló lép eléd. Egy fiolát tart feléd.\n\n„Erőt ad… vagy elátkoz.”",
eventWizardDrink: "Megiszom",
eventWizardRefuse: "Elutasítom",
combatLogEvasionActive: "{card}: kitérés aktiválva {turns} körre. Esély: {percent}%",
combatLogEvadedEnemyAttack: "Kitértél! {enemy} mellé üt. ({percent}%)",
combatLogEvasionFailed: "Megpróbáltál kitérni {enemy} támadása elől, de nem sikerült. ({percent}%)",
  },

  en: {
    combatLogEvasionActive: "{card}: evasion activated for {turns} turn(s). Chance: {percent}%",
combatLogEvadedEnemyAttack: "You evaded! {enemy} misses. ({percent}%)",
combatLogEvasionFailed: "You tried to evade {enemy}'s attack, but failed. ({percent}%)",
    combatLogEvasionActive: "{card}: {percent}% chance to evade for {turns} turns!",
combatLogEvadedEnemyAttack: "You evaded! {enemy} misses. ({percent}%)",
combatLogEvasionFailed: "You tried to evade {enemy}, but failed. ({percent}%)",
    eventWizardTitle: "Wandering Wizard",
eventWizardStory:
  "In the dust of the road, a cloaked wizard steps before you. He holds out a vial.\n\n“It grants power... or a curse.”",
eventWizardDrink: "Drink it",
eventWizardRefuse: "Refuse",
    pathFightTooltip: "A path filled with combat",
pathEliteTooltip: "A dangerously powerful enemy",
pathMysteryTooltip: "An unknown event",
pathRestTooltip: "Rest and recovery",
pathIntroWord1: "CHOOSE",
pathIntroWord2: "A",
pathIntroWord3: "PATH",
pathIconAlt: "path icon",
    travelInProgress: "Travel in progress",
clickForNewTip: "Click for a new tip!",
loadingTip: "Loading tip...",
tipsErrorConsole: "Tips error:",
                statUpgradeTitle: "Stat Upgrade",
            unspentPoints: "Unspent Points",
            strengthShort: "Strength (STR)",
            intellectShort: "Intellect (INT)",
            defenseShort: "Defense (DEF)",
            hpUpgradeLabel: "Health (Max HP +5)",
            statSaveError: "Failed to save stats.",

            homeUpper: "HOME",
        equipment: "Equipment",
        stats: "Stats",
        inventory: "Inventory",
        clickForDetails: "Click for details",
        emptySlot: "Empty slot",
        empty: "Empty",
        inventoryEmpty: "Inventory is empty",
        selected: "Selected",
        equip: "Equip",
        unequip: "Unequip",
        selectItem: "Select an item",
        deck: "Deck",
        deckNotSavedYet: "*currently the deck is not saved if you leave*",
        capacity: "Capacity",
        availableAbilities: "Available Abilities",
        activeDeck: "Active Deck",
        emptyDeck: "Empty Deck",
        cancelUpper: "CANCEL",
        saveDeck: "SAVE DECK",
        exitHouse: "Exit the house",
        spellbook: "Spellbook",
        inventoryLabel: "Inventory",
        statistics: "Statistics",
        level: "Level",
        hp: "Health",
        strength: "Strength",
        intellect: "Intellect",
        defense: "Defense",
        gold: "Gold",
        houseTutInventory: "Click Inventory (manage equipment).",
        houseTutDeck: "Click Wardrobe/Spellbook (edit deck).",
        houseTutStats: "Click Statistics (stat points).",
        houseTutExit: "Click Exit (return to the Hub).",

    menu: "Menu",
    settings: "Settings",
    logout: "Log out",
    logoutPlaceholder: "Log out (placeholder)",

    travel: "Travel",
    blacksmith: "Blacksmith",
    quests: "Quests",
    shop: "Shop",
    home: "Home",

    welcome: "Welcome!",
    hubIntroLine1:
      "This is the place where you can prepare for your next journey. Here you can upgrade, shop, take quests, and organize what you have.",
    hubIntroLine2: "When you're ready, you can move on to travel.",
    continue: "Continue",

    tutorialHome: "Click HOME (Inventory / Deck / Stats).",
    tutorialBlacksmith: "Click BLACKSMITH (upgrades).",
    tutorialShop: "Click SHOP (buying).",
    tutorialQuests: "Click QUESTS.",
    tutorialTravel: "Click TRAVEL (start adventure).",

    tab_sound: "Sound",
    tab_language: "Language",
    tab_profile: "Profile",
    tab_admin: "Admin Mode",

    soundTitle: "SOUND",
    languageTitle: "LANGUAGE",
    profileTitle: "PROFILE",
    adminTitle: "ADMIN MODE",

    music: "Music",
    effects: "Effects",
    master: "Master",

    saveLaterNote: "Placeholder: later this will be saved/applied for real.",
    languageSaveNote: "Language switches instantly and is saved to localStorage.",

    profileImage: "Profile image",
    noImage: "(No image)",
    unknown: "Unknown",
    statsTitle: "STATISTICS",
    registeredAt: "Registration date",

    enemiesDefeated: "Enemies defeated",
    bossesDefeated: "Bosses defeated",
    battlesPlayed: "Battles played",
    battlesWon: "Battles won",
    totalDamage: "Total damage",
    totalDamageTaken: "Damage taken",

    statsBackendNote: "(If stats are not sent from the backend yet, this will show “—”.)",

    editUsernameTitle: "Change username",
    editEmailTitle: "Change email",
    changeUsername: "CHANGE USERNAME",
    changeEmail: "CHANGE EMAIL",
    newValue: "New value",
    cancel: "Cancel",
    change: "Change",
    close: "Close",
    exampleEmail: "e.g. something@email.com",
    exampleUsername: "e.g. new_username",

    adminNote:
      "Enter the new value (SET). Empty field = unchanged. Saving Max HP also refills HP to full.",
    goldSet: "Gold (SET)",
    maxHpSet: "Max HP (SET)",
    xpSet: "XP (SET)",
    levelSet: "Level (SET)",
    strengthSet: "Strength (SET)",
    intellectSet: "Intellect (SET)",
    defenseSet: "Defense (SET)",
    save: "Save",
    saving: "Saving...",
    loadingSkip: "Loading screen skip",
    loadingSkipOn: "ON: the travel/loading screen is skipped instantly.",
    loadingSkipOff: "OFF: the travel/loading screen shows the countdown.",
    weapon: "Weapon",
    helmet: "Helmet",
    armor: "Armor",
    accessory: "Accessory",
    levelUpper: "LEVEL",
    goldUpper: "GOLD",
    hpUpper: "HP",
    goldLower: "gold",
    healing: "Heal",
    buyUpper: "BUY",
    sellUpper: "SELL",
    shopBuyFailed: "Purchase failed",
    shopSellFailed: "Sell failed",
    shopHealFailed: "Healing failed",
    shopStatsLoading: "Stats are still loading (full-stats).",
    shopFullHp: "You are at full HP.",
    chooseHeroTitle: "Choose a hero",
chooseHeroAlert: "Choose a hero!",
notLoggedInError: "Error: you are not logged in.",
saveClassError: "Failed to save class!",
serverError: "A server error occurred!",
unknownClass: "Unknown class.",
detailsUp: "Details ▲",
detailsDown: "Details ▼",
roleLabel: "Role",
strengthLabel: "Strength",
weaknessLabel: "Weakness",
createButton: "Create",
classLoadErrorConsole: "Failed to load classes:",

warriorName: "Warrior",
warriorShort: "A durable melee fighter that can be built in multiple ways: a safe bruiser, an aggressive damage dealer, or a steady survivor.",
warriorRole: "Versatile frontline",
warriorStrength: "Flexible build options, stable presence, and strong adaptability in different situations.",
warriorWeakness: "Bad decisions can quickly put it under pressure.",

mageName: "Mage",
mageShort: "A devastating spellcaster with high damage output, but one that can afford very few mistakes.",
mageRole: "Burst / control mage",
mageStrength: "High damage, powerful spell effects, and dangerous combos that can quickly decide a fight.",
mageWeakness: "More fragile.",

archerName: "Archer",
archerShort: "A steady ranged damage dealer that keeps constant pressure on the enemy while its pet absorbs much of the incoming damage.",
archerRole: "Stable ranged DPS",
archerStrength: "Reliable sustained damage and greater safety thanks to pet support.",
archerWeakness: "If the pet falls or cannot maintain pressure, it becomes much more vulnerable.",
menu: "Menu",
settings: "Settings",
logout: "Log out",
logoutPlaceholder: "Log out (placeholder)",
hubImageAlt: "hub",
player: "player",
welcome: "Welcome!",
hubIntroLine1:
  "This is the place where you can prepare for your next journey. Here you can upgrade, shop, take quests, and organize what you have.",
hubIntroLine2: "When you're ready, you can move on to travel.",
continue: "Continue",
travel: "Travel",
blacksmith: "Blacksmith",
quests: "Quests",
shop: "Shop",
home: "Home",
hubTutHome: "Click HOME (Inventory / Deck / Stats).",
hubTutBlacksmith: "Click BLACKSMITH (upgrades).",
hubTutShop: "Click SHOP (buying).",
hubTutQuests: "Click QUESTS.",
hubTutTravel: "Click TRAVEL (start adventure).",
loading: "Loading...",
upgradeGoldInfo: "Gold available for upgrades:",
noUpgradeableItems: "You have no more upgradeable items.",
currentItem: "Current item",
upgradedItem: "Upgraded item",
upgradeCost: "Upgrade cost",
notEnoughGoldForUpgrade: "You do not have enough gold for the upgrade.",
processing: "Processing...",
upgrade: "Upgrade",
blacksmithUpgradeFailed: "The upgrade failed.",
blacksmithServerError: "Error while connecting to the server.",
networkError: "Network error.",
loginTitle: "Login",
registerTitle: "Register",
loginSubtitle: "*Enter a username or email and password to continue*",
registerSubtitle: "*Create a new account*",
usernamePlaceholder: "Username",
identifierPlaceholder: "Username or email",
emailPlaceholder: "Email",
passwordPlaceholder: "Password",
confirmPasswordPlaceholder: "Confirm password",
registerButton: "REGISTER",
continueUpper: "CONTINUE",
alreadyHaveAccount: "Already have an account?",
switchToLogin: "Log in",
noAccountYet: "Don't have an account yet?",
switchToRegister: "Register",
loginNeedIdentifier: "Enter a username or email!",
loginNeedPassword: "Enter a password!",
loginNeedEmail: "Enter an email address!",
loginInvalidEmail: "Invalid email format!",
loginPasswordsDontMatch: "Passwords do not match!",
registerFailed: "Registration failed!",
registerLoginFailed: "You registered, but login failed.",
loginFailed: "Invalid login credentials!",
mana: "Mana",
manaAbilities: "Mana Abilities",
clickToRelease: "Click to release",
notEnoughMana: "Not enough mana",
back: "Back",
tauntActive: "TAUNT ACTIVE",
petTaunt: "PET TAUNT",
dead: "DEAD",
newEnemyUpper: "NEW ENEMY",
approachingUpper: "APPROACHING...",
remainingEnemiesUpper: "REMAINING ENEMIES",
fightUpper: "FIGHT",
noLoadedPlayer: "No player loaded. Please log in again.",
combatBegins: "THE RITUAL BEGINS...",
passTurnUpper: "PASS TURN",
stamina: "Stamina",
hits: "Hits",
taunt: "Taunt",
turns: "turns",
defeatUpper: "DEFEAT...",
victoryUpper: "VICTORY!",

combatTutEnemyTitle: "ENEMY",
combatTutEnemyText: "Here you can see the enemy HP and affixes.",
combatTutLogTitle: "COMBAT LOG",
combatTutLogText: "Here you can see what happened.",
combatTutCardsTitle: "CARDS",
combatTutCardsText: "Click a card. 1 card = 1 turn, then the enemy acts.",
combatTutManaTitle: "MANA",
combatTutManaText: "Every card gives +1 mana. From 5 mana, you can open Mana Abilities.",
combatTutPetTitle: "PET TAUNT",
combatTutPetText: "With Taunt, the pet takes the hits for a few turns. After that, it goes on cooldown.",
combatTutPassiveTitle: "PASSIVE",
combatTutPassiveText: "Warrior: the lower your HP, the harder you hit, but you also take more damage.",
combatLogGhostPhase: "Ghost: Phase – invulnerable for 1 turn!",
combatLogLichIceLance: "Lich Mage: Ice Lance – Weaken (1 turn).",
combatLogLichArcaneWard: "Lich Mage: Arcane Ward – the next hit is reduced!",
combatLogBanditGuard: "Bandit: Guard – the next hit is reduced!",

combatLogTravelPoisoned: "Travel event: you were poisoned ({turns} turns).",

combatLogArcaneDamage: "{name}: {dmg} damage.",
combatLogArcaneFullHeal: "{name}: full heal.",
combatLogArcaneBigDamage: "{name}: {dmg} massive damage!",

combatLogNotEnoughPetTauntStamina: "Not enough stamina for Pet Taunt!",
combatLogPassedTurn: "You passed your turn.",
combatLogPetTauntActivated: "Pet Taunt activated ({turns} turns). Cooldown: {cooldown}.",
combatLogPetBite: "Pet Bite: {dmg} damage!",

combatLogShieldedGuardActive: "{enemy} [Shielded] – Guard active ({hits} hits).",
combatLogEnemyPhaseBlocksAttack: "{enemy} is in Phase – the attack bounces off!",
combatLogWeakenReducedDamage: "Weaken: reduced damage!",
combatLogBerserkerRageDamage: "Berserker Rage: +{percent}% damage ({hp}/{maxHp} HP).",
combatLogExecute: "Crushing Blow – execution!",
combatLogRallyingShoutBuff: "Rallying Shout empowers your attack!",
combatLogEnemyGuardReducedHit: "{enemy} Guard: reduced hit!",
combatLogCardDealsDamage: "{card} → {enemy} takes {dmg} damage{crit}.",
combatLogCritSuffix: " (CRITICAL!)",
combatLogDrainLifeHeal: "Drain Life heals: +{heal} HP.",
combatLogEnemyPoisoned: "{enemy} is poisoned: {dmg} damage for {turns} turns.",
combatLogEnemyBleeding: "Bleeding! ({stacks} stacks) {enemy} takes damage each turn.",
combatLogEnemyBurning: "{enemy} starts burning: {dmg} damage for {turns} turns.",
combatLogEnemyStunImmune: "{enemy} cannot be stunned for {turns} more turns!",
combatLogEnemyStunnedSkip: "{enemy} is stunned and skips the next turn!",
combatLogEnemyVulnerable: "{enemy} becomes vulnerable: takes +{percent}% damage for {turns} turns!",
combatLogTravelDamageBonus: "Travel effect: +{percent}% damage",

combatLogEvasionActive: "{card}: evasion for {turns} turns!",
combatLogDefendingActiveTurns: "{card}: defense activated for {turns} turns!",
combatLogDefendingActive: "Defense activated – the next hit is reduced.",
combatLogParryStun: "Parry! {enemy} is stunned and skips the turn!",
combatLogCardPetTaunt: "Pet Taunt: the enemy attacks the pet ({turns} turns).",
combatLogCardHeals: "{card}: +{heal} HP.",
combatLogDamageBuff: "{card}: your next {turns} attack(s) deal +{percent}% damage!",
combatLogMendPet: "Mend Pet: +{heal} HP (Pet: {hp}/{maxHp})",
combatLogWeakenEnded: "Weaken has ended.",

combatLogVictoryRewards: "Victory! +{gold} gold, +{xp} XP.",

combatLogPlagueAuraPoison: "{enemy} [Plague Aura] – poisons you ({turns} turns).",
combatLogPoisonDamagePlayer: "Poison damage: {dmg} (You – {hp} HP).",
combatLogBurnDamageEnemy: "Burn damage: {dmg} ({enemy} – {hp} HP).",
combatLogPoisonDamageEnemy: "Poison damage: {dmg} ({enemy} – {hp} HP).",
combatLogBleedDamageEnemy: "Bleed: {dmg} damage ({percent}%).",
combatLogEnemyStillStunned: "{enemy} remains stunned and skips the turn!",
combatLogArcaneSurgeEnded: "Arcane Surge has ended.",
combatLogEvadedEnemyAttack: "You evaded! {enemy} misses.",
combatLogPetGuard: "Pet Guard! The pet softened the hit.",
combatLogEnemyHitsPet: "{enemy} hits the pet ({dmg} damage). (Pet: {hp}/{maxHp})",
combatLogEnemyAttacksPlayer: "{enemy} attacks ({dmg} damage).",

combatLogEnemyAmbushed: "{enemy} challenged you!",
combatLogEnemyAmbushedReinforcements: "{enemy} attacked you! (REINFORCEMENTS: +{count} enemies approaching...)",
combatLogEnemyDefeatedContinue: "{enemy} defeated...",
combatLogNewEnemyStepsIn: "! A new enemy steps in: {enemy} !",

combatLogNotEnoughStamina: "Not enough stamina! ({cost} required)",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    try {
      const saved = localStorage.getItem(LANGUAGE_LS_KEY);
      return saved === "en" ? "en" : "hu";
    } catch {
      return "hu";
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem(LANGUAGE_LS_KEY, language);
    } catch {}

    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (next) => {
    setLanguageState(next === "en" ? "en" : "hu");
  };

 const t = (key, params = {}) => {
  let text = translations[language]?.[key] ?? translations.hu?.[key] ?? key;

  if (typeof text !== "string") return key;

  for (const [paramKey, paramValue] of Object.entries(params)) {
    text = text.replaceAll(`{${paramKey}}`, String(paramValue));
  }

  return text;
};

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t,
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return ctx;
}